---
# roles/mysql/tasks/main.yml
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install mysql latest version
  # noqa package-latest
  ansible.builtin.apt:
    name: mysql-server
    state: latest

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install pymysql
  ansible.builtin.pip:
    name: pymysql
    state: present

#- name: Copy .my.cnf file for root user
#  ansible.builtin.template:
#    src: my.cnf_root.j2
#    dest: /root/.my.cnf
#    owner: root
#    mode: '0600'

#- name: Copy .my.cnf file for user
#  ansible.builtin.template:
#    src: my.cnf.j2
#    dest: /{{ mysql_user_name }}/.my.cnf
#    owner: {{ mysql_user_name }}
#    mode: '0600'

- name: Update MySQL root authentication via socket for localhost (Linux, MySQL ≥ 8.4)
  # noqa no-changed-when
  ansible.builtin.shell: >
    mysql -u root -NBe "ALTER USER 'root'@'localhost' IDENTIFIED WITH auth_socket; FLUSH PRIVILEGES;"

- name: Create new user with password
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ mysql_user_name }}"
    host: 'localhost'
    password: "{{ mysql_user_password }}"
    priv: "{{ priv }}"
    state: present
  #no_log: "{{ mysql_hide_passwords }}"  

- name: Mysql Configuration - Resetting Root Password
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock    
    login_user: root
    login_password: ''
    name: root
    host_all: true
    password: "{{ mysql_root_password }}"
  when: mysql_root_password_update | bool or mysql_root_password != ''
 
- name: Reload mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
